### PR TITLE
Updated Image Info

### PR DESCRIPTION
**Pull request by Abhi-2109**

### CODE REVIEW

**Comment by DivyanshBatham** [comment]
@Abhi-2109 There are no changes.

**Comment by Abhi-2109** [comment]
imgsrc --- > imgSrc 
image is not seen at website.

**Comment by Abhi-2109** [comment]
There was a spelling mistake  in the json file

**Comment by DivyanshBatham** [comment]
Hmm, I see the difference now. Will merge and redeploy in the evening.

**Pull request merged**
